#!/bin/sh

echo "current Wi-Fi DNS servers:"
echo "$(networksetup -getdnsservers Wi-Fi)"

case "$1" in
	local)
		networksetup -setdnsservers Wi-Fi 127.0.0.1
		;;
	none)
		networksetup -setdnsservers Wi-Fi empty
		;;
	*)
		# Google's
		networksetup -setdnsservers Wi-Fi 8.8.8.8 8.8.4.4
esac

echo ""
echo "Wi-Fi DNS servers now set to:"
echo "$(networksetup -getdnsservers Wi-Fi)"

