require("config.options")
require("config.keymaps")
require("config.colorscheme")
require("config.autocommands")
require("config.tree")
require("config.telescope")
require("config.cmp")
require("config.lsp")
require("config.lsp.null-ls")
-- require("config.treesitter")
